# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmake', models.CharField(max_length=30, verbose_name='Make')),
                ('cmodel', models.CharField(max_length=30, verbose_name='Model')),
                ('trim', models.CharField(max_length=30, verbose_name='Trim')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Year')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
