# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('due', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('importance', models.CharField(choices=[('Important/Urgent', 'Important/Urgent'), ('Important/Not urgent', 'Important/Not urgent'), ('Not important/Urgent', 'Not important/Urgent'), ('Not important/Not urgent', 'Not important/Not urgent')], max_length=50, verbose_name='Importance')),
            ],
        ),
    ]
